version: 2
updates:
  - package-ecosystem: "nuget"    
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"      
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
      dev-dependencies:
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
                        # ecosystem. Note: using "*" may open a large pull request      